var searchData=
[
  ['damages_1908',['DAMAGES',['../buffer-equal-constant-time_2_l_i_c_e_n_s_e_8txt.html#a4b3ca8042d6a421cdff623fa3ee8ffe5',1,'DAMAGES(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;LOSS OF USE, DATA, OR PROFITS;OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY:&#160;LICENSE.txt'],['../esquery_2license_8txt.html#a98a10190de258cdffe7eb0b3d3093f1b',1,'DAMAGES(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;LOSS OF USE, DATA, OR PROFITS;OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY:&#160;license.txt']]]
];
